name: application
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: SFProDisplayBold
      fonts:
        - asset: assets/fonts/sf-pro-display/sf-pro-display-bold.otf
    - family: SFProDisplayMedium
      fonts:
        - asset: assets/fonts/sf-pro-display/sf-pro-display-medium.otf
    - family: SFProDisplayRegular
      fonts:
        - asset: assets/fonts/sf-pro-display/sf-pro-display-regular.otf
    - family: SFProTextBold
      fonts:
        - asset: assets/fonts/sf-pro-text/sf-pro-text-bold.otf
    - family: SFProTextMedium
      fonts:
        - asset: assets/fonts/sf-pro-text/sf-pro-text-medium.otf
    - family: SFProTextRegular
      fonts:
        - asset: assets/fonts/sf-pro-text/sf-pro-text-regular.otf

  assets:
    - assets/images/
    - assets/icons/
